INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, 'S', 'Black', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, 'M', 'Black', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, 'L', 'Black', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, 'XL', 'Black', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, 'XXL', 'Black', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, '3XL', 'Black', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, 'S', 'Grey', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, 'M', 'Grey', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, 'L', 'Grey', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, 'XL', 'Grey', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, 'XXL', 'Grey', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'MM fashion cotton linen New style slimming wide-leg pants', 17.5, '3XL', 'Grey', 200, 0, 1, '/image/pant/1.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Large Size Dress Wide Leg Pants Set 2018 New Style Korean Style Summer Short-sleeved Fat Mm Favorite Slimming Bell Sleeve Set', 16.5, 'M', 'Green', 200, 0, 2, '/image/pant/2.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Large Size Dress Wide Leg Pants Set 2018 New Style Korean Style Summer Short-sleeved Fat Mm Favorite Slimming Bell Sleeve Set', 16.5, 'L', 'Green', 200, 0, 2, '/image/pant/2.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Large Size Dress Wide Leg Pants Set 2018 New Style Korean Style Summer Short-sleeved Fat Mm Favorite Slimming Bell Sleeve Set', 16.5, 'XL', 'Green', 200, 0, 2, '/image/pant/2.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Large Size Dress Wide Leg Pants Set 2018 New Style Korean Style Summer Short-sleeved Fat Mm Favorite Slimming Bell Sleeve Set', 16.5, 'XXL', 'Green', 200, 0, 2, '/image/pant/2.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Large Size Dress Wide Leg Pants Set 2018 New Style Korean Style Summer Short-sleeved Fat Mm Favorite Slimming Bell Sleeve Set', 16.5, '3XL', 'Green', 200, 0, 2, '/image/pant/2.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Navy', 13.2, 'S', 'Blue', 200, 0, 3, '/image/pant/3.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Navy', 13.2, 'M', 'Blue', 200, 0, 3, '/image/pant/3.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Navy', 13.2, 'L', 'Blue', 200, 0, 3, '/image/pant/3.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Navy', 13.2, 'XL', 'Blue', 200, 0, 3, '/image/pant/3.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Navy', 13.2, 'XXL', 'Blue', 200, 0, 3, '/image/pant/3.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Navy', 13.2, '3XL', 'Blue', 200, 0, 3, '/image/pant/3.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Black', 11.8, 'S', 'Black', 200, 0, 4, '/image/pant/4.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Black', 11.8, 'M', 'Black', 200, 0, 4, '/image/pant/4.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Black', 11.8, 'L', 'Black', 200, 0, 4, '/image/pant/4.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Black', 11.8, 'XL', 'Black', 200, 0, 4, '/image/pant/4.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Black', 11.8, 'XXL', 'Black', 200, 0, 4, '/image/pant/4.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Casual Pockets Straight Elastic Waist Harem Pants For Women Black', 11.8, '3XL', 'Black', 200, 0, 4, '/image/pant/4.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'plus size 4XL Women pants Casual Pants High Waist Fashion Stretch Pencil pants Cotton Skinny Trousers for women White - intl', 17.23, 'S', 'White', 200, 0, 5, '/image/pant/5.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'plus size 4XL Women pants Casual Pants High Waist Fashion Stretch Pencil pants Cotton Skinny Trousers for women White - intl', 17.23, 'M', 'White', 200, 0, 5, '/image/pant/5.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'plus size 4XL Women pants Casual Pants High Waist Fashion Stretch Pencil pants Cotton Skinny Trousers for women White - intl', 17.23, 'L', 'White', 200, 0, 5, '/image/pant/5.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'plus size 4XL Women pants Casual Pants High Waist Fashion Stretch Pencil pants Cotton Skinny Trousers for women White - intl', 17.23, 'XL', 'White', 200, 0, 5, '/image/pant/5.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'plus size 4XL Women pants Casual Pants High Waist Fashion Stretch Pencil pants Cotton Skinny Trousers for women White - intl', 17.23, 'XXL', 'White', 200, 0, 5, '/image/pant/5.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'plus size 4XL Women pants Casual Pants High Waist Fashion Stretch Pencil pants Cotton Skinny Trousers for women White - intl', 17.23, '3XL', 'White', 200, 0, 5, '/image/pant/5.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'VONDA Women Plus Wide Leg Trousers Plaid Check Vintage Casual Loose Pockets Long Pants', 12.5, 'M', 'Grey', 200, 0, 6, '/image/pant/6.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'VONDA Women Plus Wide Leg Trousers Plaid Check Vintage Casual Loose Pockets Long Pants', 12.5, 'L', 'Grey', 200, 0, 6, '/image/pant/6.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'VONDA Women Plus Wide Leg Trousers Plaid Check Vintage Casual Loose Pockets Long Pants', 12.5, 'XL', 'Grey', 200, 0, 6, '/image/pant/6.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'VONDA Women Plus Wide Leg Trousers Plaid Check Vintage Casual Loose Pockets Long Pants', 12.5, 'XXL', 'Grey', 200, 0, 6, '/image/pant/6.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'VONDA Women Plus Wide Leg Trousers Plaid Check Vintage Casual Loose Pockets Long Pants', 12.5, '3XL', 'Grey', 200, 0, 6, '/image/pant/6.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', '2019 Summer New Style Plus-sized Womens Dress 200 of Fat Mm Capri Wide Leg Pants Female Slimming Loose Pants
', 7.7, 'XL', 'Black', 200, 0, 7, '/image/pant/7.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', '2019 Summer New Style Plus-sized Womens Dress 200 of Fat Mm Capri Wide Leg Pants Female Slimming Loose Pants
', 7.7, 'XXL', 'Black', 200, 0, 7, '/image/pant/7.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', '2019 Summer New Style Plus-sized Womens Dress 200 of Fat Mm Capri Wide Leg Pants Female Slimming Loose Pants
', 7.7, '3XL', 'Black', 200, 0, 7, '/image/pant/7.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', '2019 Summer New Style Plus-sized Womens Dress 200 of Fat Mm Capri Wide Leg Pants Female Slimming Loose Pants
', 7.7, 'XL', 'Grey', 200, 0, 7, '/image/pant/7.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', '2019 Summer New Style Plus-sized Womens Dress 200 of Fat Mm Capri Wide Leg Pants Female Slimming Loose Pants
', 7.7, 'XXL', 'Grey', 200, 0, 7, '/image/pant/7.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', '2019 Summer New Style Plus-sized Womens Dress 200 of Fat Mm Capri Wide Leg Pants Female Slimming Loose Pants
', 7.7, '3XL', 'Grey', 200, 0, 7, '/image/pant/7.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Plus size loose Bottoms Elasticated waist Casual Plaid Pants for women', 24.5, 'XL', 'Red', 200, 0, 8, '/image/pant/8.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Plus size loose Bottoms Elasticated waist Casual Plaid Pants for women', 24.5, 'XXL', 'Red', 200, 0, 8, '/image/pant/8.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Plus size loose Bottoms Elasticated waist Casual Plaid Pants for women', 24.5, '3XL', 'Red', 200, 0, 8, '/image/pant/8.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Plus size loose Bottoms Elasticated waist Casual Plaid Pants for women', 24.5, 'XL', 'Black', 200, 0, 8, '/image/pant/8.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Plus size loose Bottoms Elasticated waist Casual Plaid Pants for women', 24.5, 'XXL', 'Black', 200, 0, 8, '/image/pant/8.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Plus size loose Bottoms Elasticated waist Casual Plaid Pants for women', 24.5, '3XL', 'Black', 200, 0, 8, '/image/pant/8.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Plus size loose Bottoms Elasticated waist Casual Plaid Pants for women', 24.5, 'XL', 'Brown', 200, 0, 8, '/image/pant/8.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Plus size loose Bottoms Elasticated waist Casual Plaid Pants for women', 24.5, 'XXL', 'Brown', 200, 0, 8, '/image/pant/8.jpg');
INSERT INTO product (type_of_product,description, price, size, color, available, sold, img_id, img_path) VALUES ('pant', 'Plus size loose Bottoms Elasticated waist Casual Plaid Pants for women', 24.5, '3XL', 'Brown', 200, 0, 8, '/image/pant/8.jpg');